- .github/workflows/swift-ci.yml
- .swift-format
- .swift-format.json
- .swiftlint.yml
let's see if anything broke moving this over
Fixes #
**Checklist**
> ci: add ci

- Examples/AccountAlias/main.swift
- Examples/AccountAllowance/main.swift
- Examples/ConsensusPubSub/main.swift
- Examples/ConsensusPubSubChunked/main.swift
- Examples/ConsensusPubSubWithSubmitKey/main.swift
- Package.swift
- Sources/Hedera/PrivateKey.swift
- Sources/Hedera/Topic/TopicCreateTransaction.swift
- Sources/Hedera/TopicMessageQuery.swift
- Sources/Hedera/Transaction/TransactionSources.swift
- Sources/Hedera/TransactionId.swift
- Closes #47 
- Closes #48 
- Closes #49 
- Closes #50 
- Closes #51
**Checklist**
> Feat/chore: add more examples

- .github/workflows/swift-ci.yml
5.6 still doesn't pass CI because swift ICE _sigh_.
Fixes #
**Checklist**
> ci: Try enabling swift ~5.6~ and 5.8

- Sources/Hedera/Account/AccountCreateTransaction.swift
alias as aliasKey doesn't actually exist,
confusing I know
Fixes #
**Checklist**
> fix(AccountCreateTransaction): evmAddress is actually alias

- Sources/Hedera/TransferTransaction.swift
> chore: document behavior of `expectedDecimals`

- Package.resolved
- Package.swift
- Sources/Hedera/PrivateKey.swift
- Sources/Hedera/PublicKey.swift
- Tests/HederaTests/PublicKeyTests.swift
> chore: update and properly constrain secp256k1

- Package.resolved
- Sources/Hedera/CustomFee.swift
- Sources/Hedera/Token/NftId.swift
- Sources/Hedera/Token/TokenCreateTransaction.swift
- Sources/Hedera/TransferTransaction.swift
- Tests/HederaE2ETests/Account/AccountAllowanceApprove.swift
- Tests/HederaE2ETests/Token/FungibleToken.swift
- Tests/HederaE2ETests/Token/Nft.swift
- Tests/HederaE2ETests/Token/TokenAssociate.swift
- Tests/HederaE2ETests/Token/TokenBurn.swift
- Tests/HederaE2ETests/Token/TokenDelete.swift
- Tests/HederaE2ETests/Token/TokenDissociate.swift
- Tests/HederaE2ETests/Token/TokenFeeScheduleUpdate.swift
- Tests/HederaE2ETests/Token/TokenFreeze.swift
- Tests/HederaE2ETests/Token/TokenGrantKyc.swift
- Tests/HederaE2ETests/Token/TokenInfo.swift
- Tests/HederaE2ETests/Token/TokenMint.swift
- Tests/HederaE2ETests/Token/TokenNftInfo.swift
- Tests/HederaE2ETests/Token/TokenNftTransfer.swift
- Tests/HederaE2ETests/Token/TokenRevokeKyc.swift
- Tests/HederaE2ETests/Token/TokenTransfer.swift
- Tests/HederaE2ETests/Token/TokenUnfreeze.swift
- Tests/HederaE2ETests/Token/TokenUpdate.swift
- Tests/HederaE2ETests/Token/TokenWipe.swift
- Tests/HederaE2ETests/XCTestCase+Extensions.swift
- Fixes #115 
- Fixes #116 
- Fixes #119 
- Fixes #120
- Fixes #121 
- Fixes #122 
- Fixes #125 
- Fixes #124
- Fixes #132  
- Fixes #133 
- Fixes #130 
- Fixes #126 
- Fixes #129 
- Fixes #140 
- Fixes #134 
- Fixes #136 
- Fixes #137 
**Checklist**
> more E2E tests

- Tests/HederaE2ETests/Schedule/ScheduleSign.swift
- Tests/HederaE2ETests/Token/TokenCreate.swift
Signed-off-by: Ricky Saechao <76449893+RickyLB@users.noreply.github.com>
- Fixes https://github.com/hashgraph/hedera-sdk-swift/issues/118
- Fixes https://github.com/hashgraph/hedera-sdk-swift/issues/156
Fixes #
**Checklist**
> test(e2e): TokenCreate & ScheduledSign

- Sources/Hedera/Crypto/CryptoPem.swift
- Sources/Hedera/Crypto/Pkcs5AlgorithmIdentifier.swift
- Sources/Hedera/Crypto/Sec1.swift
- Sources/Hedera/PrivateKey.swift
- Sources/Hedera/PublicKey.swift
- Tests/HederaTests/PrivateKeyTests.swift
- Tests/HederaTests/PublicKeyTests.swift
> feat(key): Support Openssl style keys

- Sources/Hedera/TransferTransaction.swift
> feat(transfer-tx): Add get token/nftTransfers to public API

- Package.resolved
> chore: update package.resolved

- Sources/Hedera/ChunkedTransaction.swift
- Sources/Hedera/Transaction.swift
- Tests/HederaTests/SignatureTests.swift
- add `getSignatures` to `Transaction`
- add `getAllSignatures` to `ChunkedTransaction`
- https://github.com/hashgraph/hedera-sdk-swift/issues/205
Fixes #
**Checklist**
> feat(transaction): getSignatures

- Tests/HederaTests/CryptoAesTests.swift
- Tests/HederaTests/CryptoSha2Tests.swift
- Tests/HederaTests/CryptoSha3Tests.swift
- Tests/HederaTests/DurationTests.swift
- Tests/HederaTests/FileAppendTransactionTests.swift
- Tests/HederaTests/Resources.swift
- Tests/HederaTests/__Snapshots__/DurationTests/testToFromProtobuf.1.txt
- Tests/HederaTests/__Snapshots__/FileAppendTransactionTests/testSerialize.1.txt
- https://github.com/hashgraph/hedera-sdk-swift/issues/301
- https://github.com/hashgraph/hedera-sdk-swift/issues/302
- https://github.com/hashgraph/hedera-sdk-swift/issues/303
- https://github.com/hashgraph/hedera-sdk-swift/issues/307
- https://github.com/hashgraph/hedera-sdk-swift/issues/191
Fixes #
**Checklist**
> More unit tests

- .github/CODEOWNERS
Misaligned Code ownership in original gha/ci update
Fixes #
**Checklist**
> fix: Updated codeowners for SDK repo

- .github/CODEOWNERS
Updates per Q3 audit findings.
Related to #363 
**Checklist**
> ci: Update per Q3 audit findings

- Examples/AddNftAllowance/main.swift
- Examples/InitializeClientWithMirrorNetwork/main.swift
- Package.swift
- Sources/Hedera/Client/Client.swift
- Sources/Hedera/Client/Network.swift
- Sources/Hedera/NodeAddress.swift
- Tests/HederaE2ETests/Client.swift
- https://github.com/hashgraph/hedera-sdk-swift/issues/406
Fixes #
**Checklist**
> Initialize client with Mirror Network

- Examples/AddNftAllowance/main.swift
- Tests/HederaE2ETests/NodeCreateTransaction.swift
This PR includes an e2e test for `NodeCreate` that tests against the Solo tool.
- https://github.com/hashgraph/hedera-sdk-swift/issues/393
Fixes #
- resolve warnings in example
**Checklist**
> Add E2E: NodeCreateTransaction w/ Solo

- Package.swift
This PR narrows the version of the SDK dependencies using best practices.
Fixes #469 
**Checklist**
> chore: update dependencies to be up to version numbers

- Sources/Hiero/Version.swift
This PR updates the version for `v0.42.0` release.
> chore: Release v0.42.0

- Examples/CreateAccount/main.swift
- Sources/Hiero/Client/Client.swift
- Sources/Hiero/Client/MirrorNetwork.swift
- Sources/Hiero/Client/Network.swift
- Sources/Hiero/Version.swift
This PR fixes some issues with selection of plaintext vs TLS connections for mirror nodes and consensus nodes.
> fix: better coordination of tls/plaintext connections

- Sources/Hiero/Version.swift
This PR prepares for the v0.43.0 release.
> chore(release): v0.43.0
