hiero-ledger/hiero-sdk-swift

Sources/Hedera/MirrorQuery.swift
Sources/Hedera/NodeAddressBookQuery.swift
Sources/Hedera/Timestamp.swift
Sources/Hedera/TopicMessage.swift
Sources/Hedera/TopicMessageQuery.swift
Sources/Hedera/TransactionId.swift
Sources/Hedera/TransactionResponse.swift
Taskfile.yml

This is the Swift equivalent of hashgraph/hedera-sdk-rust#498
- Fixes #71 
- Fixes #72 
**Checklist**

refactor: Make TopicMessage match other SDKs

---

Sources/Hedera/ChunkedTransaction.swift
Sources/Hedera/Client.swift
Sources/Hedera/Contract/ContractCreateFlow.swift
Sources/Hedera/Execute.swift
Sources/Hedera/Operator.swift
Sources/Hedera/PingQuery.swift
Sources/Hedera/PrivateKey.swift
Sources/Hedera/Query.swift
Sources/Hedera/QueryCost.swift
Sources/Hedera/Signer.swift
Sources/Hedera/TopicMessageQuery.swift
Sources/Hedera/Transaction.swift
Sources/Hedera/Transaction/TransactionSources.swift

Add remaining transaction requirements

---

Sources/Hedera/Contract/DelegateContractId.swift
Sources/Hedera/Key.swift

feat: Add DelegateContractId

---

.gitmodules
Package.resolved
Package.swift
README.md
Sources/Hedera/Client.swift
Sources/Hedera/Client/Network.swift
Sources/Hedera/Contract/ContractId.swift
Sources/Hedera/EntityId.swift
Sources/Hedera/Schedule/ScheduleId.swift
Sources/Hedera/Token/TokenId.swift
Sources/Hedera/Topic/TopicId.swift
Sources/Hedera/Transaction/TransactionSources.swift
Sources/Hedera/TransactionReceipt.swift
Sources/HederaProtobufs/Mirror/mirror_consensus_service.grpc.swift
Sources/HederaProtobufs/Mirror/mirror_network_service.grpc.swift
Sources/HederaProtobufs/Services/consensus_service.grpc.swift
Sources/HederaProtobufs/Services/crypto_service.grpc.swift
Sources/HederaProtobufs/Services/file_service.grpc.swift
Sources/HederaProtobufs/Services/freeze_service.grpc.swift
Sources/HederaProtobufs/Services/network_service.grpc.swift
Sources/HederaProtobufs/Services/schedule_service.grpc.swift
Sources/HederaProtobufs/Services/smart_contract_service.grpc.swift
Sources/HederaProtobufs/Services/token_service.grpc.swift
Sources/HederaProtobufs/Services/util_service.grpc.swift

Notably there's a bump to SwiftAtomics that lets me get rid of some `@unchecked Sendable` wrappers for types that should've been `Sendable` in the first place
Fixes #
**Checklist**

Bump deps (protobufs are deps)

---

Sources/Hedera/Transaction.swift

Found this bug in the rust SDK, and checked here to ensure it either wasn't here or got fixed as well... It was here
Fixes #
**Checklist**

fix: ensure transaction.toBytes signs the sources if they exist

---

Sources/Hedera/Account/AccountBalance.swift
Sources/Hedera/Account/AccountInfo.swift
Sources/Hedera/AssessedCustomFee.swift
Sources/Hedera/Contract/ContractFunctionResult.swift
Sources/Hedera/Contract/ContractLogInfo.swift
Sources/Hedera/Contract/ContractNonceInfo.swift
Sources/Hedera/Contract/DelegateContractId.swift
Sources/Hedera/ExchangeRates.swift
Sources/Hedera/File/FileContentsQuery.swift
Sources/Hedera/File/FileContentsResponse.swift
Sources/Hedera/Key.swift
Sources/Hedera/KeyList.swift
Sources/Hedera/Schedule/ScheduleInfo.swift
Sources/Hedera/StakingInfo.swift
Sources/Hedera/Token/TokenAssociation.swift
Sources/Hedera/Token/TokenNftTransfer.swift
Sources/Hedera/TopicMessage.swift
Sources/Hedera/TransactionReceipt.swift
Sources/Hedera/TransactionRecord.swift
Sources/Hedera/TransactionResponse.swift
Sources/Hedera/Transfer.swift

- Add various `Sendable` conformances (They should exist, just, easy to miss them)
- Add `exchangeRates` to `TransactionReceipt`.
-  Note that unlike JS, Java, and Go, (but like CPP), this is the current *and next*. However, an equivalent `exchangeRate` property exists anyway, so, in practice this isn't really a divergence.
- Fixes #259 
**Checklist**

receipt exchange rate

---

Examples/ScheduleMultiSigTransaction/main.swift
Sources/Hedera/Checksum.swift
Sources/Hedera/Client/Client.swift
Sources/Hedera/Client/Network.swift
Sources/Hedera/Crypto/Pkcs5.swift
Sources/Hedera/Crypto/Pkcs5Pbkdf2.swift
Sources/Hedera/Ethereum/EvmAddress.swift
Sources/Hedera/FeeSchedule/RequestType.swift
Sources/Hedera/FeeSchedule/TransactionFeeSchedule.swift
Sources/Hedera/File/FileInfo.swift
Sources/Hedera/Hbar.swift
Sources/Hedera/NodeAddress.swift
Sources/Hedera/PaymentTransaction.swift
Sources/Hedera/PrivateKey.swift
Sources/Hedera/PublicKey.swift
Sources/Hedera/SolidityAddress.swift
Sources/Hedera/Transaction.swift
Sources/Hedera/TransactionId.swift
Sources/Hedera/TransactionReceipt.swift

Mostly internal refactors with no outward facing changes...
Except:
- change!: `RequestType` no longer has the `.none` variant, instead an Optional (`RequestType?`) should be used.
- change!: `TransactionReceipt.topicRunningHash` is now `Data` instead of a base64 string
- fix: Actually serialize `TransactionReceipt.topicRunningHash` in `toProtobuf` impl (this is something that can be noticed, but it isn't exactly breaking).
Catalog of internal changes for reference purposes:
- refactor: use `HError.basicParse(..)` instead of `HError(kind: basicParse, description: ..)` (they do the same thing but the former is both less likely to mess with IDEs and is shorter)
- change: remove transaction ID from ScheduleMultiSigTransaction example because it isn't actually used (despite …

Clean up various todos

---

Tests/HederaE2ETests/Token/TokenUnpause.swift
Tests/HederaE2ETests/Transaction/TransactionReceipt.swift
Tests/HederaE2ETests/Transaction/TransactionRecord.swift

- Fixes https://github.com/hashgraph/hedera-sdk-swift/issues/135
- Fixes https://github.com/hashgraph/hedera-sdk-swift/issues/157
- Fixes https://github.com/hashgraph/hedera-sdk-swift/issues/158
Fixes #
**Checklist**

More e2e tests

---

.env.example
.github/workflows/swift-ci.yml
README.md
Tests/HederaE2ETests/Config.swift

- Added local node to e2e tests
- In the README.md, there are instructions on running e2e tests
- https://github.com/hashgraph/hedera-sdk-swift/issues/314
- https://github.com/hashgraph/hedera-sdk-swift/issues/315
Fixes #
**Checklist**

chore: run local node in e2e tests

---

Package.resolved
Package.swift
Sources/Hedera/CustomFee.swift
Sources/Hedera/Protobufs/Rational+ProtobufCodable.swift

This PR upgrades `swift_numberkit` version (`2.4.2` -> `2.6.0`) and fixes the `UInt64` incompatibility with `Rational` protocol.
- https://github.com/hashgraph/hedera-sdk-swift/issues/377
Fixes #
**Checklist**

fix: upgrade swift_numberkit and remove UInt64 casts

---

Sources/Hedera/Token/TokenRejectFlow.swift
Tests/HederaE2ETests/Token/TokenRejectFlow.swift

This PR contains a `TokenRejectflow` for `TokenRejectTransaction` that will automatically disassociate the token.
- https://github.com/hashgraph/hedera-sdk-swift/issues/375
Fixes #
**Checklist**

Token Reject Flow

---

Examples/AddNftAllowance/main.swift
Package.swift

By adding an example to demonstrate how to manage NFT allowances in the Swift SDK. 
The example includes step-by-step processes for:
-  Setting up the SDK client with the necessary operator account and key.
-  Creating a unique NFT and minting tokens with metadata.
-  Creating spender and receiver accounts.
-  Associating spender and receiver accounts with the NFT.
-  Granting allowance for specific NFT serials to a spender account.
-  Executing an NFT transfer using the approved allowance.
-  Revoking the allowance for certain NFT serials.
-  Attempting a transfer after revocation to confirm permission removal.
-  Cleaning up resources by deleting tokens and accounts.
**Testing**:
- Due to not having access to a macOS or iOS environment, I am unable to run the example …

Add Swift example for managing NFT allowances

---

Sources/HederaTCK/SDKClient.swift
Sources/HederaTCK/main.swift

This PR adds the JSON-RPC `deleteAccount` to service `AccountDeleteTransaction` TCK tests.
Fixes #404 
**Checklist**

feat(TCK): Implement JSON-RPC endpoint for `AccountDeleteTransaction`

---

Sources/Hedera/Timestamp.swift
Sources/HederaTCK/JSONHelper.swift
Sources/HederaTCK/SDKClient.swift
Sources/HederaTCK/main.swift

This PR adds the JSON-RPC `updateAccount` to service `AccountUpdateTransaction` TCK tests. A tweak was made to the SDK itself as well to allow `Timestamp`s to parse unsigned integers to protobuf fields.
Fixes #403 
**Checklist**

feat(TCK): Implement JSON-RPC endpoint for `AccountUpdateTransaction`

---

Package.resolved
Package.swift
Sources/Hedera/Bip32Utils.swift
Sources/Hedera/Data+Extensions.swift
Sources/Hedera/Mnemonic/Mnemonic.swift
Sources/Hedera/PrivateKey.swift
Tests/HederaTests/MnemonicTests.swift
Tests/HederaTests/PrivateKeyTests.swift
hedera-sdk-swift/Package.swift

This PR incorporates Mnemonic.toStandardECDSAsecp256k1PrivateKey()
- https://github.com/hashgraph/hedera-sdk-swift/issues/390
**Fixes**
**Checklist**

toECDSAsecp256k1PrivateKey & derive legacy ecdsa private key

---

.github/CODEOWNERS

- Replaces devops-ci with platform-ci
- Fixes issue with codeowners on .github/workflows
- Updates license codeowners
Fixes #426

chore: Update codeowners to include platform-ci

---

Package.resolved
Package.swift
Sources/Hedera/Crypto/CryptoSha3.swift
Sources/Hedera/Rlp.swift
Sources/HederaTCK/SDKClient.swift
Tests/HederaE2ETests/EthereumTransaction.swift
Tests/HederaE2ETests/Topic/TopicMessageSubmit.swift
Tests/HederaTests/ContractInfoTests.swift
Tests/HederaTests/ContractLogInfoTests.swift
Tests/HederaTests/DelegateContractIdTests.swift
Tests/HederaTests/FileInfoTests.swift
Tests/HederaTests/KeyTests.swift
Tests/HederaTests/MnemonicTests.swift
Tests/HederaTests/NftIdTests.swift
Tests/HederaTests/PrivateKeyTests.swift
Tests/HederaTests/StakingInfoTests.swift
Tests/HederaTests/TransactionFeeScheduleTests.swift

This PR replaces `CryptoSwift` library with OpenSSL for `keccak256` hash encryption.
- https://github.com/hiero-ledger/tsc/issues/29
- https://github.com/hashgraph/hedera-sdk-swift/issues/425
Fixes #
**Checklist**

Use OpenSSL for keccak256 encryption

---

.github/CODEOWNERS

Update the CODEOWNERS file for the move to `hiero-ledger` organization.
**Related Issue(s)**:
Fixes #431

ci: update CODEOWNERS file for hiero repo move

---

.gitmodules
README.md
Sources/Hedera/TransactionId.swift

- https://github.com/hiero-ledger/hiero-sdk-swift/issues/427

Handle overflow for TransactionId timestamp

---

.github/CODEOWNERS

The github-committers team has been removed. Taking it out of codeowners

chore: Update codeowners to remove github-committers

---

Sources/Hiero/Topic/TopicCreateTransaction.swift
Tests/HieroTests/TopicCreateTransactionTests.swift

This PR enables HIP-1021 and properly sets the `autoRenewAccountId` of a created topic to the fee payer.
Fixes #440

feat: set `autoRenewAccountId` for new topic to fee payer

---

Sources/Hiero/Ethereum/EthereumFlow.swift
Sources/Hiero/Version.swift

This PR deprecates `EthereumFlow`, as `EthereumTransaction` can now deal with large files.
Fixes #476 
**Checklist**

chore: deprecate EthereumFlow

---

Sources/Hiero/Client/Client.swift
Sources/Hiero/Client/MirrorNetwork.swift
Sources/Hiero/Client/Network.swift
Sources/Hiero/NodeAddress.swift

This PR fixes an issue with `NodeAddressBookQuery` where it was unable to connect with solo. The cause of this is because it was using a TLS connection when solo is only using plaintext. So now localhost connections default to plaintext. This also adjusts node addressing and tests `forMirrorNetwork` against solo and is confirmed working.
Fixes #443 
**Checklist**

fix: mirror node grpc connection issue and test forMirrorNetwork
